// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Product struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Price int    `json:"price"`
}

type ProductInput struct {
	Name  string `json:"name"`
	Price int    `json:"price"`
}

type Query struct {
}
